### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by NNickey** [orels1/discord-token-generator#1]
```
C:\Users\Administrator\Downloads\discord-token-generator-master\discord-token-generator-master\api\discord.js:20
router.get('/callback', catchAsync(async (req, res) => {
                                         ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\Downloads\discord-token-generator-master\discord-token-generator-master\server.js:20:25)
    at Module._compile (module.js:570:32)
```

Versions
```
C:\Users\Administrator\Downloads\discord-token-generator-master\discord-token-generator-master>npm version
{ 'discord-token-generator': '1.0.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.4',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.89',
  zlib: '1.2.8' }
```

**Comment by orels1** [comment]
I suppose you use an outdated version of nodeJS. this one requires node 7.10

**Comment by johnsampson** [comment]
Confirming that an upgrade of node resolves this issue.
